INSERT INTO site_types (type_name, dual_state)
VALUES ('Nhà hàng', 'DUAL'),
       ('Nhà hàng thức ăn nhanh', 'AMENITY'),
       ('Nhà hàng thuần chay', 'AMENITY'),
       ('Nhà hàng thịt nướng', 'AMENITY'),
       ('Nhà hàng Brunch', 'AMENITY'),
       ('Quán ăn nhỏ', 'DUAL'),
       ('Nhà hàng thực phẩm lành mạnh', 'AMENITY'),
       ('Nhà hàng chay', 'AMENITY'),
       ('Nhà hàng cao cấp', 'DUAL'),
       ('Nhà hàng hải sản', 'AMENITY'),
       ('Nhà điều hành tour', 'AMENITY'),
       ('Nhà hàng gia đình', 'DUAL'),
       ('Nhà hàng bít tết', 'AMENITY'),
       ('Quán tapas', 'AMENITY'),
       ('Quán mì', 'AMENITY'),
       ('Nhà hàng cơm', 'DUAL'),
       ('Quán cà phê', 'AMENITY'),
       ('Quầy xúc xích nóng', 'AMENITY'),
       ('Quán bánh mì', 'DUAL'),
       ('Nhà hàng buffet', 'DUAL'),
       ('Quầy đồ ăn nhẹ', 'AMENITY'),
       ('Điểm du lịch', 'ATTRACTION'),
       ('Khách sạn', 'AMENITY'),
       ('Khu nghỉ dưỡng khách sạn (Resort hotel)', 'ATTRACTION'),
       ('Quán bia thủ công', 'DUAL'),
       ('Hoa viên', 'ATTRACTION'),
       ('Nhà vườn cho thuê', 'DUAL'),
       ('Cửa hàng thực phẩm', 'AMENITY'),
       ('Nhà nghỉ dưỡng', 'DUAL'),
       ('Homestay', 'DUAL'),
       ('Pub', 'AMENITY'),
       ('Căn hộ nghỉ dưỡng', 'DUAL'),
       ('Khu cắm trại', 'ATTRACTION'),
       ('Phòng GYM', 'AMENITY'),
       ('Nhà thờ', 'DUAL'),
       ('Villa', 'DUAL'),
       ('Nông trại', 'ATTRACTION'),
       ('Vườn', 'ATTRACTION'),
       ('Vườn cây', 'ATTRACTION'),
       ('Công viên', 'ATTRACTION'),
       ('Nông trại cắm trại', 'ATTRACTION'),
       ('Khu đi bộ', 'AMENITY'),
       ('Cơ quan du lịch lặn', 'AMENITY'),
       ('Công viên sinh thái', 'ATTRACTION'),
       ('Công viên tưởng niệm', 'ATTRACTION'),
       ('Rừng quốc gia', 'ATTRACTION'),
       ('Công viên đồng quê', 'ATTRACTION'),
       ('Vườn bách thảo', 'ATTRACTION'),
       ('Quán ăn', 'DUAL');
