INSERT INTO aspects_by_type (type_id, aspect) VALUES
(3, 'Phí vào cửa'),
(2, 'Phí vào cửa'),
(3, 'Phí vào cửa'),
(3, 'Dùng bữa'),
(4, 'Đo huyết áp'),
(5, 'Dùng bữa'),
(6, 'Dùng bữa'),
(7, 'Dùng bữa'),
(8, 'Dùng bữa'),
(9, 'Dùng bữa'),
(10, 'Dùng bữa'),
(11, 'Dùng bữa'),
(12, 'Dùng bữa'),
(13, 'Dùng bữa'),
(14, 'Dùng bữa'),
(15, 'Dùng bữa'),
(16, 'Dùng bữa'),
(17, 'Dùng bữa'),
(18, 'Dùng bữa'),
(19, 'Dùng bữa'),
(20, 'Dùng bữa'),
(21, 'Thưởng thức'),
(22, 'Dùng bữa'),
(23, 'Dùng bữa'),
(24, 'Dùng bữa'),
(25, 'Dùng bữa'),
(26, 'Vào cửa'),
(27, 'Dùng bữa'),
(28, 'Dùng bữa'),
(53, 'Dùng bữa');